import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { ReactNode } from "react";
import Sidebar from "@/components/sidebar/Sidebar";
import "./globals.css";
import Header from "@/components/header/Header";

const poppins = Inter({
  weight: ["400", "600"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-black text-white min-h-screen lg:grid lg:grid-rows-1 lg:grid-cols-[1fr_5fr]`}
      >
        <Sidebar />
        <main>
          <Header />
          <div className="p-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
