import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className="h-screen grid grid-rows-1 grid-cols-[1fr_5fr]">
        {/* SIDEBAR COMPONENT */}
        <Sidebar />
        <div>{children}</div>
      </body>
    </html>
  );
}
